name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - run: |
          mkdir -p dist

          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi

          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CGO_ENABLED=0 \
          go build \
            -ldflags="-s -w" \
            -o dist/db-${{ matrix.goos }}-${{ matrix.goarch }}${EXT} \
            ./cmd/db

      - uses: actions/upload-artifact@v4
        with:
          name: db-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - run: find dist -type f

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*